### ISSUE TITLE
Add means to ensure users are authenticated with nickserv?

### ISSUE THREAD

**Issue by patcon** [nandub/hubot-irc#103]
The gittip project is considering how to use hubot to deploy from the public #gittip channel on freenode. Still not sure if it's a good idea, but we would definitely need a way to ensure that only the designated irc users are allowed to "become" privileged from hubot's point of view.

Links:
- http://stackoverflow.com/questions/1682920/determine-if-a-user-is-idented-on-irc
- https://github.com/github/hubot-scripts/blob/master/src/scripts/auth.coffee

**Comment by chrisdotcode** [comment]
It's a bit late now, but I think that @patcon's solution looks pretty good for this sort of thing. (and may gratipay rest in peace).
