### ISSUE TITLE
Will not run on Heroku or OpenShift

### ISSUE THREAD

**Issue by CodisRedding** [nandub/hubot-irc#119]
I can hubot from my machine, but no luck when I deploy it to Heroku or OpenShift. my profile is:

web: bin/hubot -a irc -n mybotsname

When I ssh into heroku/openshift and manually run hubot the console output only shows that it's successfully connected to Redis and nothing more. My local hubot will connect to Redis and then connect to IRC. I've checked the env vars and they are correct on all platforms.

Any ideas>

**Comment by chrisdotcode** [comment]
@CodisRedding, #160 seems to imply that freenode requires SASL auth when connecting from Heroku IPs.

Try that and see if it works, if your problem was not already solved.
