### ISSUE TITLE
A command that sends messages to the specified channel will only work if you send it on the channel

### ISSUE THREAD

**Issue by RockyTV** [nandub/hubot-irc#128]
I have this command I made for my bot that sends a custom message to the specified channel. However, if you send the command via PM, it wont work. If you send it on the channel, it works.

Not sure if this was already fixed.

**Comment by chrisdotcode** [comment]
Since @RockyTV hasn't replied in 3 years, I'm going to go ahead and close this for now.

**Comment by RockyTV** [comment]
I'm sorry, I might have lost the exact code I had then. If this is still an issue with the latest release I'll reopen the issue.

**Comment by chrisdotcode** [comment]
Sounds good.
