### ISSUE TITLE
Add SASL support

### ISSUE THREAD

**Issue by martinb3** [nandub/hubot-irc#131]
The node-irc library added SASL support about a year ago, but hubot-irc doesn't pass the option along to the nodeirc library. The PR to node-irc is https://github.com/martynsmith/node-irc/pull/125.

I think the change would be as trivial as adding `sasl: <true/false>` to https://github.com/nandub/hubot-irc/blob/master/src/irc.coffee#L173-L184, hooking it into the options of hubot-irc as appropriate.

I would love to find a way to send arbitrary additional `key: value` options to node-irc from hubot-irc, so that this doesn't need to be done for every obscure option to node-irc. It _does_ look like the fork you are maintaining of node-irc includes the sasl bits.

**Comment by powellchristoph** [comment]
Any update on this?

**Comment by rodrigoaguilera** [comment]
I think some work is being done here https://github.com/nandub/hubot-irc/pull/160

**Comment by tmccleve** [comment]
Updated at #167

**Comment by chrisdotcode** [comment]
Resolved by #167.
