### ISSUE TITLE
Allow a robot name different from the irc nick

### ISSUE THREAD

**Issue by mowings** [nandub/hubot-irc#132]
We'd like our bot to be addressable via a name other than the irc nickname -- in our case, a '!' sign. This is mainly for convenience. The current hubot-irc automatically sets the robot name to the irc nickname from HUBOT_IRC_NICK. While this is probably fine in 90% of all cases, our fork adds an additional envar, HUBOT_IRC_ROBOT_NAME to allow changing this.

**Comment by Fedcomp** [comment]
Any progress on this? hubot react only on irc nickname and i want it to react on alias.

**Comment by chrisdotcode** [comment]
cf. #133
