### ISSUE TITLE
We need more help

### ISSUE THREAD

**Issue by nandub** [nandub/hubot-irc#141]
As you can see we have a lot of issues and pull requests that need to be taken care of but because of time or availability, I haven't been able to work on the project and @jgable and other contributors cannot work on this project full time and I for one do not know enough of coffee-script to be able to help the project.

So with that out of the way I like to ask anyone that uses the adapter and have time to work on the project if you interested please let me know via email at nandub at nandub.info.  @jgable if you want to add more here please go ahead.

**Comment by jgable** [comment]
I've started a new job and don't have much time to help out with the
project any more.  Anyone with some node-irc and coffeescript knowledge
should be able to contribute effectively here.

**Comment by parkr** [comment]
I'd be happy to lend a hand reviewing!

**Comment by nandub** [comment]
@parkr thanks I added you as a collaborator, when your ready start away.

**Comment by chrisdotcode** [comment]
Hi!
