### ISSUE TITLE
missing dependencies on heroku 

### ISSUE THREAD

**Issue by Jaglag** [nandub/hubot-irc#142]
i using latest version of hubot-irc on Heroku everytime i update the bot:

 node-icu-charset-detector@0.0.7 cant be compiled cause of missing libicu on heroku.

is there maybe a workaround for this?

**Comment by parkr** [comment]
What depends upon `node-icu-charset-detector`?

**Comment by Jaglag** [comment]
you need libicu for compiling it on heroku as far as  i know.

At first, install libicu into your system (See this instruction for details)
thats from node-icu-charset-detector^^

dont know how to get that on heroku?

**Comment by Jaglag** [comment]
heres a error log:

http://pastebin.com/sguYbP20

**Comment by parkr** [comment]
It's a dependency of the `irc` package. I just filed it here: https://github.com/martynsmith/node-irc/issues/327

**Comment by Jaglag** [comment]
hmm k ty
