### ISSUE TITLE
Deploying multiple hubots from the same server

### ISSUE THREAD

**Issue by rhiaro** [nandub/hubot-irc#144]
Hey, I'm not sure what's going on. I have a hubot instance running in a docker container on a server (everything Ubuntu) that works fine. I try to deploy a different hubot instance in a different docker container (so totally separate but identical environment), on the same server and I get `Error: Cannot find module 'hubot-irc'`. The same container deploys on a _different_ server just fine, so there's nothing wrong with the build itself.

**Comment by parkr** [comment]
Is `hubot-irc` in the `node_modules` directory? How do you deploy/install your hubot?

**Comment by rhiaro** [comment]
Yes, `hubot-irc` is there. 

I run `rhiaro/hubotplus` docker container (http://registry.hub.docker.com/u/rhiaro/hubotplus, derived from `guttertec/hubot`) then launch hubot inside the container from bash, nothing fancy. Notes at https://github.com/rhiaro/rhiarobot/blob/master/README.md

It's an identical setup to the other bot that's already running, just with different scripts.

**Comment by chrisdotcode** [comment]
@rhiaro If this issue is still unresolved, comment and I'll re-open this.
