### ISSUE TITLE
Hubot doesn't respond on channels starting with !

### ISSUE THREAD

**Issue by TeroPihlaja** [nandub/hubot-irc#145]
I tested the bot configs on a #channel and the bot responded as expected. However when I changed the channel to the actual !channel (on IRCnet if that matters), the bot seems to not respond to the commands.

**Comment by jametsi** [comment]
+1 I also encountered this today

**Comment by jametsi** [comment]
#158 fixes this

**Comment by chrisdotcode** [comment]
Closed by #158.
