### ISSUE TITLE
TLS Support for Hubot

### ISSUE THREAD

**Issue by chron0** [nandub/hubot-irc#149]
Ahoy, more and more IRC networks move towards more secure connection restrictions, to deal with rogue government agencies and don't allow anything below TLS1.1. I couldn't get to connect with the IRC adapter to a couple of those nets, maybe I'm doing it wrong or is it not yet implemented?

**Comment by strugee** [comment]
@chron0 you need to export `HUBOT_IRC_USESSL` in the environment.

**Comment by codec** [comment]
@strugee I have the same issues and I definitely have `HUBOT_IRC_USESSL` in my environment.

I've decided to run Hubot in "plaintext" through stunnel, connecting to the ircd.

**Comment by strugee** [comment]
@codec did you try turning on debugging logs? What do they say?

**Comment by chrisdotcode** [comment]
I'm 99% positive this is fixed. I have `HUBOT_IRC_USESSL` on in my person hubot instance, and it's working.

Don't forget - if you're using SSL to make sure to change your port as well. For instance, `irc.freenode.net` over SSL uses `6697` ***not*** `6667`.
