### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by chrisdotcode** [nandub/hubot-irc#170]
cf. #156

**Comment by chrisdotcode** [comment]
I personally would like to update irc to [matrix-org/node-irc](https://github.com/matrix-org/node-irc) instead of [martynsmith/node-irc](https://github.com/martynsmith/node-irc), which seems to be no longer maintained.

**Comment by nandub** [comment]
if it moves the project forward, I don’t have any objections.

**Comment by chrisdotcode** [comment]
Closed in `develop`.
