### ISSUE TITLE
Does not reconnect automatically

### ISSUE THREAD

**Issue by X-dark** [nandub/hubot-irc#93]
I got a small problem with my Internet connection which get cut every 12h (on the router not on the server). Weechat reconnects automatically to IRC when Internet is back but hubot does not and does not even seem to notice the loss of connectivity.

**Comment by zachlatta** [comment]
Any updates on this? This is causing us some trouble when we run into occasional connection issues.

**Comment by tchncs** [comment]
\*push*

**Comment by parkr** [comment]
Hi folks. I'm unable to take a look at this at the moment and it seems @nandub is busy as well. If someone sufficiently bugged by this bug is able to figure out how to solve it, I would be more than happy to take a look at a pull request. Please do not :+1: or bump this issue anymore.

**Comment by kirbo** [comment]
auto-reconnect (and auto-join on reconnect) would be more than appreciated +1
